plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

android {
  namespace 'expo.modules.podcastauto'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

dependencies {
  implementation 'androidx.core:core-ktx:1.15.0'
  implementation 'androidx.media3:media3-common:1.9.0'
  implementation 'androidx.media3:media3-session:1.9.0'
  implementation 'androidx.media3:media3-exoplayer:1.9.0'
  implementation 'androidx.media3:media3-datasource:1.9.0'
}
